name = "BlockNLPModelsPlasmo"
uuid = "1491da42-d7d6-4405-9b13-bbc4ec68cdae"
authors = ["Sungho Shin <sshin@anl.gov>"]
version = "0.1.0"

[deps]
Plasmo = "d3f7391f-f14a-50cc-bbe4-76a32d1bad3c"
BlockNLPModels = "26fb23fc-4a37-41a0-8f1d-1a5a3817d965"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Plasmo = "0.5"
BlockNLPModels = "0.1"
NLPModelsJuMP = "0.11"
NLPModelsIpopt = "0.9"
Ipopt = "1"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
LinearAlgebra =  "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"

[targets]
test = ["Test", "NLPModelsIpopt", "LinearAlgebra", "Ipopt"]
